# -*- coding: utf-8 -*-
"""Movie Recommendation System

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uphxLtJWMg_bP5sUbDyYS1WphnNBpnlt
"""

import pandas as pd

import numpy as np

movies=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Movies%20Recommendation.csv')

movies.head()

movies.info()

movies.shape

movies.columns

movies_features=movies[['Movie_Genre','Movie_Production_House','Movie_Spoken_Language','Movie_Cast','Movie_Director']].fillna('')

movies_features.shape

movies_features

x = movies_features['Movie_Genre'] + ' ' + movies_features['Movie_Production_House'] + ' ' + movies_features['Movie_Spoken_Language'] + ' ' + movies_features['Movie_Cast'] + ' ' + movies_features['Movie_Director'] + ' '

x.shape

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

x = tfidf.fit_transform(x)

x.shape

print(x)

from sklearn.metrics.pairwise import cosine_similarity

Similarity_Score=cosine_similarity(x)

Similarity_Score

Similarity_Score.shape

Favourite_Movie_Name = input ("Enter Your Favourite Movie Name: ")

All_Movies_Title_List=movies['Movie_Title'].tolist()

import difflib

Movie_Recommendation = difflib.get_close_matches(Favourite_Movie_Name,All_Movies_Title_List)

print(Movie_Recommendation )

Close_Match=Movie_Recommendation[0]

print(Close_Match)

Index_Of_Close_Match_Movie = movies[movies.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_Of_Close_Match_Movie)

Recommendation_Score = list(enumerate(Similarity_Score[Index_Of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

Sorted_Similiar_Movies = sorted(Recommendation_Score,key=lambda x:x[1],reverse= True )
print(Sorted_Similiar_Movies)

print('Top 30 Movies Suggested For You : \n')
i=1
for movie in Sorted_Similiar_Movies:
  index=movie[0]
  title_from_index = movies[movies.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i,'.',title_from_index)
    i+=1

Movie_Name = input('Enter Your Favourite Movie Name : ')
list_of_all_titles = movies['Movie_Title'].tolist()
Find_Close_Match = difflib.get_close_matches(Movie_Name,list_of_all_titles)
Close_Match=Find_Close_Match[0]
Index_Of_Movie = movies[movies.Movie_Title == Close_Match]['Movie_ID'].values[0]
Recommendation_Score = list(enumerate(Similarity_Score[Index_Of_Movie]))
Sorted_Similiar_Movies = sorted(Recommendation_Score,key=lambda x:x[1],reverse= True )
print('Top 30 Movies Suggested For You : \n')
i=1
for movie in Sorted_Similiar_Movies:
  index=movie[0]
  title_from_index = movies[movies.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i,'.',title_from_index)
    i+=1